# Set the port number to run on
server:
    port: 5000

# ===============================
# = DATA SOURCE
# ===============================

# Connection url for the database "localwomen"
spring:
    datasource:
        url: jdbc:mysql://localwomen.cmx1vpsrbwxr.us-west-2.rds.amazonaws.com:3306/localwomen?useSSL=false
        username: localwomen
        password: L0calW0men
        testWhileIdle: true
        validationQuery: SELECT 1

# ===============================
# = JPA / HIBERNATE
# ===============================
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect

# ===============================
# = Mailer
# ===============================
    mail:
        host: smtp.gmail.com
        username: treble2001@gmail.com
        password: cfl5747
        properties:
            mail:
                debug: false
                smtp:
                    auth: true
                    ssl:
                        enable: true
                    socketFactory:
                        port: 465
                        class: javax.net.ssl.SSLSocketFactory
                        fallback: false

# ===============================
# = Email Accounts
# ===============================
orders:
    email:
        account:
            orders: anelis1982@hotmail.com
            accounts: aidannelis@gmail.com