# Set the port number to run on
server:
    port: 5000

# ===============================
# = DATA SOURCE
# ===============================

# Connection url for the database "localwomen"
spring:
    datasource:
        url: jdbc:mysql://localwomendevdb.cmx1vpsrbwxr.us-west-2.rds.amazonaws.com:3306/localwomen?useSSL=false
        username: localwomen
        password: L0calW0men
        testWhileIdle: true
        validationQuery: SELECT 1

# ===============================
# = JPA / HIBERNATE
# ===============================
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect

# ===============================
# = Mailer
# ===============================
    mail:
        #host: email-smtp.eu-west-1.amazonaws.com
        host: email-smtp.us-west-2.amazonaws.com
        port: 465
        protocol: smtps
        username: AKIAJ7SXLBST4573IKNQ
        password: AgNmrDsz3PIYYQG84dYERWuN4MKhUroZhlfEIsB6OPAD
        #username: orders@localwomensnews.com
        #password: SX9a5g
        properties:
            mail:
                debug: true
                smtp:
                    auth: true
                    ssl:
                        enable: true
                    socketFactory:
                        port: 25
                        class: javax.net.ssl.SSLSocketFactory
                        fallback: true
                    transport:
                        protocol: smtps
                smtps:
                    auth: true

# ===============================
# = Email Accounts
# ===============================
orders:
    email:
        account:
            orders: treble00_01@hotmail.com
            accounts: krisawatson@yahoo.co.uk